### ISSUE TITLE
External Mixin crash on 1.14.4 on world load

### ISSUE THREAD

**Issue by Cynosphere** [copygirl/Wearables#5]
`Mixin apply failed fabric-events-interaction-v0.mixins.json:MixinServerPlayerInteractionManager -> net.minecraft.server.network.ServerPlayerInteractionManager: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Invalid descriptor on fabric-events-interaction-v0.mixins.json:MixinServerPlayerInteractionManager->@Inject::handler$startBlockBreak$zbl000(Lnet/minecraft/util/math/BlockPos;Lnet/minecraft/util/math/Direction;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V! Expected (Lnet/minecraft/util/math/BlockPos;Lnet/minecraft/server/network/packet/PlayerActionC2SPacket$Action;Lnet/minecraft/util/math/Direction;ILorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V but found (Lnet/minecraft/util/math/BlockPos;Lnet/minecraft/util/math/Direction;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V`

I dunno how helpful this will be cause the crash is somewhere else that Wearables doesn't even use, but it was the only thing that fixed the crash when I removed it.

**Comment by copygirl** [comment]
Not quite sure what's going on. Perhaps updating the mapping could solve this issue..?

**Comment by Cynosphere** [comment]
Mapping updates didn't fix anything, will wait for a 1.14.4 build to be actually put out.
